CC=arm-linux-gcc

//CFLAGS=$(shell pkg-config --cflags gconf-2.0)
//LIBS=$(shell pkg-config --libs gconf-2.0)

#CFLAGS+= -g -Wall -I. -DHARLEY
CFLAGS+= -O6 -I. -Wall -DHARLEY

OBJS:= gpsdata.o webgpsd.o web.o kmlzipper.o harley.o

all: webgpsd devgpsrc j1850 hogdev

webgpsd: $(OBJS)
	$(CC) -o $@ $^ $(LIBS)

web.o: web.c satstat.h dogmap.h radfmt.h hogstat.h

%.h : %.html
	./html2head $@

clean:
	rm -f webgpsd $(OBJS) kml2kmz dogmap.h satstat.h radfmt.h hogstat.h *~ hogdev j1850 devgpsrc
